services:
  db:
    image: 'postgres:15'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: default-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "default-db"]
      interval: 30s
      timeout: 5s
      retries: 5

  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis/:/data

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

volumes:
  pgdata: